server-address: 172.18.241.206

spring:
  data:
    redis:
      host: ${server-address}
      port: 6379
      database: 1
      password: wei5877261
      sentinel:
        master: master
        nodes:
          - 127.0.0.1:26379
          - 127.0.0.1:26380
          - 127.0.0.1:26381
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-jdbc.yaml
    hikari:
      initialization-fail-timeout: 30
      minimum-idle: 5
      connection-timeout: 10000
  rabbitmq:
    host: ${server-address}
    port: 5672
    username: root
    password: wei5877261
    virtual-host: /url-convert
    connection-timeout: 500ms
    #生产者确认，当消息到达exchange是返回ACK，否则返回NACK
    publisher-confirm-type: correlated
    #生产者退回，消息到达交换机后但路由失败，把消息返回生产者
    publisher-returns: true
    template:
      #路由失败返回
      mandatory: true
      #重试
      retry:
        enabled: true
        initial-interval: 500ms
        multiplier: 1
        max-attempts: 3
    listener:
      direct:
        prefetch: 1
        acknowledge-mode: manual