spring:
  application:
    name: url-convert-backend
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: debian-server
      port: 6379
      database: 1
      password: wei5877261
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-jdbc.yaml
  rabbitmq:
    host: debian-server
    port: 5672
    username: root
    password: wei5877261
    virtual-host: /url-convert
    connection-timeout: 500ms
    #生产者确认，生产者返回
    publisher-confirm-type: correlated
    publisher-returns: true

    template:
      #路由失败返回
      mandatory: true
      #重试
      retry:
        enabled: true
        initial-interval: 500ms
        multiplier: 1
        max-attempts: 3
    listener:
      direct:
        prefetch: 1



mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0