spring:
  application:
    name: url-convert-backend
  threads:
    virtual:
      enabled: true
  profiles:
    active: prod

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0